/*
 * AdvancedPhyML.java
 *
 * Created on 07 September 2007, 08:23
 */

package topali.gui.dialog.jobs.tree.phyml;

import java.util.List;

import javax.swing.*;

import topali.data.*;
import topali.data.models.*;
import topali.i18n.Text;
import topali.var.utils.Utils;

/**
 *
 * @author  dlindn
 */
public class AdvancedPhyML extends javax.swing.JPanel {
    
	SequenceSet ss;
	PhymlResult result;
	
    /** Creates new form AdvancedPhyML */
    public AdvancedPhyML(SequenceSet ss, TreeResult result) {
    	this.ss = ss;
		this.result = new PhymlResult();
        initComponents();
        initValues();
        
        if(result!=null)
        	initPrevResult((PhymlResult)result);
    }
    
    private void initValues() {
    	SequenceSetProperties params = ss.getProps();
		
		List<Model> mlist = ModelManager.getInstance().listPhymlModels(ss.getProps().isNucleotides());
		String[] models = new String[mlist.size()];
		for(int i=0; i<mlist.size(); i++)
				models[i] = mlist.get(i).getName();
		
		ComboBoxModel cm = new DefaultComboBoxModel(models);
		this.subModel.setModel(cm);
		
		Model m = params.getModel();
		if(Utils.indexof(models, m.getName())==-1) {
			if(ss.getProps().isNucleotides())
				m = ModelManager.getInstance().generateModel(Prefs.phyml_dnamodel_default, m.isGamma(), m.isInv());
			else
				m = ModelManager.getInstance().generateModel(Prefs.phyml_proteinmodel_default, m.isGamma(), m.isInv());
		}
		
		this.subModel.setSelectedItem(m.getName());
		
		this.gamma.setSelected(params.getModel().isGamma());
		this.inv.setSelected(params.getModel().isInv());
		
		SpinnerNumberModel mNBoot = new SpinnerNumberModel(Prefs.phyml_bootstrap, 0, 1000, 10);
		this.bootstraps.setModel(mNBoot);
    }
    
    public void setDefaults() {
		SequenceSetProperties params = ss.getProps();
		
		List<Model> mlist = ModelManager.getInstance().listPhymlModels(ss.getProps().isNucleotides());
		String[] models = new String[mlist.size()];
		for(int i=0; i<mlist.size(); i++)
				models[i] = mlist.get(i).getName();
		
		ComboBoxModel cm = new DefaultComboBoxModel(models);
		this.subModel.setModel(cm);
		
		Model m = params.getModel();
		if(Utils.indexof(models, m.getName())==-1) {
			if(ss.getProps().isNucleotides())
				m = ModelManager.getInstance().generateModel(Prefs.phyml_dnamodel_default, m.isGamma(), m.isInv());
			else
				m = ModelManager.getInstance().generateModel(Prefs.phyml_proteinmodel_default, m.isGamma(), m.isInv());
		}
		
		this.subModel.setSelectedItem(m.getName());
		
		this.gamma.setSelected(params.getModel().isGamma());
		this.inv.setSelected(params.getModel().isInv());
		
		SpinnerNumberModel mNBoot = new SpinnerNumberModel(Prefs.phyml_bootstrap_default, 0, 1000, 10);
		this.bootstraps.setModel(mNBoot);
	}
    
    private void initPrevResult(PhymlResult res) {
    	this.bootstraps.setValue(res.bootstrap);
    }
    
    public PhymlResult onOK() {
		
		String name = (String)subModel.getSelectedItem();
		boolean g = gamma.isSelected();
		boolean i = inv.isSelected();
		
		ss.getProps().setModel(ModelManager.getInstance().generateModel(name, g, i));
		
		result.model = ss.getProps().getModel();
		result.bootstrap = (Integer)bootstraps.getValue();
		
		Prefs.phyml_bootstrap = result.bootstrap;
		
		return result;
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subModel = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        inv = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        gamma = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        bootstraps = new javax.swing.JSpinner();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(Text.get("Model_Settings")));

        jLabel8.setText(Text.get("Substitution_Model"));

        subModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        subModel.setToolTipText("null");

        jLabel9.setText(Text.get("Invariant_Sites"));

        inv.setToolTipText("null");
        inv.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        inv.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel10.setText(Text.get("Gamma"));

        gamma.setToolTipText("null");
        gamma.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        gamma.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(jLabel10)
                    .add(jLabel8))
                .add(44, 44, 44)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(inv)
                    .add(gamma)
                    .add(subModel, 0, 277, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(subModel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(inv)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(gamma))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel10)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText(Text.get("Bootstrap_Runs"));

        bootstraps.setToolTipText("null");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel6)
                .add(57, 57, 57)
                .add(bootstraps, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .add(26, 26, 26))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(bootstraps, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bootstraps;
    private javax.swing.JCheckBox gamma;
    private javax.swing.JCheckBox inv;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox subModel;
    // End of variables declaration//GEN-END:variables
    
}
