/*
 * QuickTreeDialogPanel.java
 *
 * Created on 06 December 2007, 08:05
 */

package topali.gui.dialog.jobs.tree.quicktree;

import javax.swing.SpinnerNumberModel;

import topali.data.Prefs;
import topali.i18n.Text;

/**
 *
 * @author  dlindn
 */
public class QuickTreeDialogPanel extends javax.swing.JPanel {

    /** Creates new form QuickTreeDialogPanel */
    public QuickTreeDialogPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        estimate = new javax.swing.JCheckBox();
        tstvlabel = new javax.swing.JLabel();
        alphalabel = new javax.swing.JLabel();
        bootstrapLabel = new javax.swing.JLabel();
        bs = new javax.swing.JSpinner();
        alpha = new javax.swing.JSpinner();
        tstv = new javax.swing.JSpinner();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings:"));

        estimate.setSelected(true);
        estimate.setText("Automatically estimate parameters");
        estimate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        estimate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        estimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimateActionPerformed(evt);
            }
        });

        tstvlabel.setText("Transition/transversion ratio: ");
        tstvlabel.setEnabled(false);

        alphalabel.setText("Rate heterogeneity (alpha): ");
        alphalabel.setEnabled(false);

        bootstrapLabel.setText("Number of bootstrap runs:");

        SpinnerNumberModel mod2 = new SpinnerNumberModel(Prefs.qt_bootstrap, 0, 500, 10);
        bs.setModel(mod2);

        alpha.setEnabled(false);
        SpinnerNumberModel mod1 = new SpinnerNumberModel(Prefs.qt_alpha, 0.1d, 100d, 0.1d);
        alpha.setModel(mod1);

        tstv.setEnabled(false);
        SpinnerNumberModel mod0 = new SpinnerNumberModel(Prefs.qt_tstv, 0d, 100d, 0.1d);
        tstv.setModel(mod0);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tstvlabel)
                            .add(alphalabel)
                            .add(bootstrapLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .add(alpha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .add(tstv, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .add(estimate))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(estimate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tstvlabel)
                    .add(tstv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(alphalabel)
                    .add(alpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bootstrapLabel)
                    .add(bs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void estimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimateActionPerformed
        if(estimate.isSelected()) {
            tstvlabel.setEnabled(false);
//            tstvlabel2.setEnabled(false);
//            tstvlabel3.setEnabled(false);
            tstv.setEnabled(false);
            alphalabel.setEnabled(false);
//            alphalabel2.setEnabled(false);
//            alphalabel3.setEnabled(false);
            alpha.setEnabled(false);
        }
        else {
            tstvlabel.setEnabled(true);
//            tstvlabel2.setEnabled(true);
//            tstvlabel3.setEnabled(true);
            tstv.setEnabled(true);
            alphalabel.setEnabled(true);
//            alphalabel2.setEnabled(true);
//            alphalabel3.setEnabled(true);
            alpha.setEnabled(true);
        }
    }//GEN-LAST:event_estimateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSpinner alpha;
    public javax.swing.JLabel alphalabel;
    public javax.swing.JLabel bootstrapLabel;
    public javax.swing.JSpinner bs;
    public javax.swing.JCheckBox estimate;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JSpinner tstv;
    public javax.swing.JLabel tstvlabel;
    // End of variables declaration//GEN-END:variables

}
