/*
 * MTDialogPanel.java
 *
 * Created on 15 October 2007, 14:51
 */

package topali.gui.dialog.jobs.mt;

import java.awt.Component;
import java.util.*;

import javax.swing.*;

import topali.data.ModelTestResult;
import topali.data.models.*;
import topali.gui.Prefs;

/**
 *
 * @author  dlindn
 */
public class MTDialogPanel extends javax.swing.JPanel {
    
	ModelTestResult res;
	boolean dna;
	
    /** Creates new form MTDialogPanel */
    public MTDialogPanel(ModelTestResult res, boolean dna) {
    	this.res = (res==null) ? new ModelTestResult() : res;
    	this.dna = dna;
        initComponents();
        
        DefaultComboBoxModel mod = new DefaultComboBoxModel(new String[] {ModelTestResult.TYPE_PHYML, ModelTestResult.TYPE_MRBAYES});
        models.setModel(mod);
        
        DefaultComboBoxModel mod2 = new DefaultComboBoxModel(new String[] {ModelTestResult.SAMPLE_SEQLENGTH, ModelTestResult.SAMPLE_ALGNSIZE});
        sampleSize.setModel(mod2);
        
        models.setSelectedItem(Prefs.ms_models);
    	gamma.setSelected(Prefs.ms_gamma);
    	inv.setSelected(Prefs.ms_inv);
    	sampleSize.setSelectedItem(Prefs.ms_samplesize);
    	
    	if(res!=null)
    		initPrevResult(res);
    }
    
    private void initPrevResult(ModelTestResult res) {
    	this.models.setSelectedItem(res.type);
    	this.gamma.setSelected(res.models.get(0).isGamma());
    	this.inv.setSelected(res.models.get(0).isInv());
    	this.sampleSize.setSelectedItem(res.sampleSize);
    }
    
    public ModelTestResult getResult() {
    	
    	List<Model> availModels = null;
		if(this.models.getSelectedItem().equals(ModelTestResult.TYPE_PHYML)) {
			availModels = ModelManager.getInstance().listPhymlModels(dna);
		}
		else if(this.models.getSelectedItem().equals(ModelTestResult.TYPE_MRBAYES)) { 
			availModels = ModelManager.getInstance().listMrBayesModels(dna);
		}
		ArrayList<Model> models = new ArrayList<Model>();
		for(Model m : availModels) {
				Model m1 = ModelManager.getInstance().generateModel(m.getName(), false, false);
				models.add(m1);
				if(gamma.isSelected()) {
					Model m2 = ModelManager.getInstance().generateModel(m.getName(), true, false);
					models.add(m2);
				}
				if(inv.isSelected()) {
					Model m3 = ModelManager.getInstance().generateModel(m.getName(), false, true);
					models.add(m3);
				}
				if(gamma.isSelected()&&inv.isSelected()) {
					Model m4 = ModelManager.getInstance().generateModel(m.getName(), true, true);
					models.add(m4);
				}
		}
		res.models = models;
		res.type = (String)this.models.getSelectedItem();
		res.sampleCrit = (String)this.sampleSize.getSelectedItem();
		
		Prefs.ms_gamma = gamma.isSelected();
		Prefs.ms_inv = inv.isSelected();
		Prefs.ms_models = (String)this.models.getSelectedItem();
		Prefs.ms_samplesize = (String)sampleSize.getSelectedItem();
    	return this.res;
    }
    
    public String getSampleSizeSelection() {
    	return (String)sampleSize.getSelectedItem();
    }
    
    public void setDefaults() {
    	models.setSelectedIndex(0);
    	gamma.setSelected(true);
    	inv.setSelected(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        models = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gamma = new javax.swing.JCheckBox();
        inv = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sampleSize = new javax.swing.JComboBox();

        jLabel1.setText("Models:");

        models.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PhyML", "MrBayes" }));

        jLabel2.setText("Gamma:");

        jLabel3.setText("Invariant Sites:");

        gamma.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        gamma.setMargin(new java.awt.Insets(0, 0, 0, 0));

        inv.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        inv.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel4.setText("AIC2/BIC Calculation:");

        jLabel5.setText("Sample Size =");

        sampleSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sequence Length", "Alignment Size" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inv)
                            .addComponent(gamma)
                            .addComponent(models, 0, 113, Short.MAX_VALUE)
                            .addComponent(sampleSize, 0, 113, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(models, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(gamma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(inv))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sampleSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox gamma;
    private javax.swing.JCheckBox inv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox models;
    private javax.swing.JComboBox sampleSize;
    // End of variables declaration//GEN-END:variables
    
}
