/*
 * WebPanel2.java
 *
 * Created on 16 December 2005, 09:29
 */

package topali.gui.dialog.settings;

import java.awt.event.*;
import javax.swing.*;

import topali.gui.*;

import doe.*;

class WebPanel extends javax.swing.JPanel implements ActionListener
{
	private SpinnerNumberModel secModel, portModel;
	
	public WebPanel()
	{
		initComponents();
		createControls();
	}
	
	private void createControls()
	{		
		secModel = new SpinnerNumberModel(Prefs.web_check_secs, 10, 300, 10);
		secSpin.setModel(secModel);
		portModel = new SpinnerNumberModel(Prefs.web_proxy_port, 1, 65535, 1);
		portSpin.setModel(portModel);
		
		useProxy.addActionListener(this);
		if (Prefs.web_proxy_server.equals(" ") == false)
			proxyName.setText(Prefs.web_proxy_server);
		
		setDefaults(false);
	}
	
	void setDefaults(boolean reset)
	{
		if (reset)
			Prefs.setWebDefaults();
		
		topaliURL.setText(Prefs.web_topali_url);		
		secSpin.setValue(Prefs.web_check_secs);		
		checkUpdates.setSelected(Prefs.web_check_startup);
		useProxy.setSelected(Prefs.web_proxy_enable);
		
		checkStates(useProxy.isSelected());
	}
	
	boolean isOK()
	{
		if (topaliURL.getText().length() == 0)
		{
			MsgBox.msg("Please ensure a URL is entered for the TOPALi web services.", MsgBox.ERR);
			return false;
		}
		
		if (useProxy.isSelected() && proxyName.getText().length() == 0)
		{
			MsgBox.msg("Please ensure a proxy server name has been entered.",
				MsgBox.ERR);
			return false;
		}
		
		Prefs.web_topali_url = topaliURL.getText();
		Prefs.web_check_secs = secModel.getNumber().intValue();
		
		Prefs.web_check_startup = checkUpdates.isSelected();
		Prefs.web_proxy_enable = useProxy.isSelected();
		Prefs.web_proxy_server = proxyName.getText();
		Prefs.web_proxy_port = portModel.getNumber().intValue();
		
		return true;
	}
	
	public void actionPerformed(ActionEvent e)
	{
		boolean state = useProxy.isSelected();
		
		checkStates(state);
		if (state)
			proxyName.requestFocus();
	}
	
	private void checkStates(boolean state)
	{
		proxyName.setEnabled(state);
		portSpin.setEnabled(state);
		serverLabel.setEnabled(state);
		portLabel.setEnabled(state);
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topaliURL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        secSpin = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        useProxy = new javax.swing.JCheckBox();
        serverLabel = new javax.swing.JLabel();
        proxyName = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        portSpin = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        checkUpdates = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Phylogenetic web services:"));
        jLabel1.setText("TOPALi web services:");

        jLabel2.setText("Check job progress every:");

        secSpin.setFont(new java.awt.Font("Dialog", 0, 11));

        jLabel3.setText("seconds");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(secSpin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3))
                    .add(topaliURL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(topaliURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(secSpin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Other settings:"));
        useProxy.setText("Use a proxy server for all web connections:");
        useProxy.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useProxy.setMargin(new java.awt.Insets(0, 0, 0, 0));

        serverLabel.setText("Server name:");

        portLabel.setText(" Port:");

        portSpin.setFont(new java.awt.Font("Dialog", 0, 11));

        jLabel4.setText("(Changes to proxy settings will only take effect after TOPALi is restarted)");

        checkUpdates.setText("Check for updated versions of TOPALi at program startup");
        checkUpdates.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkUpdates.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(serverLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(proxyName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(portLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(portSpin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(checkUpdates)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(useProxy, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .add(192, 192, 192))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel4)
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(checkUpdates)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(useProxy)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(serverLabel)
                    .add(proxyName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(portLabel)
                    .add(portSpin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkUpdates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel portLabel;
    private javax.swing.JSpinner portSpin;
    private javax.swing.JTextField proxyName;
    private javax.swing.JSpinner secSpin;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JTextField topaliURL;
    private javax.swing.JCheckBox useProxy;
    // End of variables declaration//GEN-END:variables
    
}
