/*
 * BootstrapDialog.java
 *
 * Created on 20 November 2007, 16:02
 */

package topali.gui.tree;

import javax.swing.SpinnerNumberModel;

import topali.var.utils.*;

/**
 *
 * @author  dlindn
 */
public class BootstrapDialog extends javax.swing.JDialog {
    
    double threshold = -1;
    String replacement = null;
    
    /** Creates new form BootstrapDialog */
    public BootstrapDialog(java.awt.Frame parent, boolean modal, String tree) {
        super(parent, modal);
        initComponents();
        
        double[] tmp = TreeUtils.analyzeBootstrapValues(tree);
        SpinnerNumberModel mod;
        if(tmp[2]<=1) { //we're dealing with probabilities
        	double min = MathUtils.round(tmp[0], 2);
        	double value = MathUtils.round(tmp[1], 2);
        	double max = MathUtils.round(tmp[2], 2);
        	mod = new SpinnerNumberModel(value, min, max+0.01, 0.01);
        } 
        else { // or "real" bootstrap values
        	int min = (int)(tmp[0]);
        	int value = (int)(tmp[1]);
        	int max = (int)(tmp[2]);
        	mod = new SpinnerNumberModel(value, min, max+1, 1);
        }
        thresholdSpinner.setModel(mod);
        
        pack();
        setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        thresholdSpinner = new javax.swing.JSpinner();
        replace = new javax.swing.JCheckBox();
        repLabel = new javax.swing.JLabel();
        repChar = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Bootstrap Values");
        setResizable(false);

        jLabel1.setText("Remove bootstrap values");

        jLabel2.setText("< ");

        replace.setText("Replace bootstrap values");
        replace.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        replace.setMargin(new java.awt.Insets(0, 0, 0, 0));
        replace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceActionPerformed(evt);
            }
        });

        repLabel.setText("with: ");
        repLabel.setEnabled(false);

        repChar.setText("*");
        repChar.setEnabled(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(replace)
                    .add(layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(okButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cancelButton))
                            .add(layout.createSequentialGroup()
                                .add(repLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(repChar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(thresholdSpinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(thresholdSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(21, 21, 21)
                .add(replace)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(repLabel)
                    .add(repChar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        threshold = Double.parseDouble(thresholdSpinner.getValue().toString());
        if(replace.isSelected()) 
            replacement = repChar.getText();
        else
            replacement = null;
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void replaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceActionPerformed
        repLabel.setEnabled(true);
        repChar.setEnabled(true);
    }//GEN-LAST:event_replaceActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BootstrapDialog(new javax.swing.JFrame(), true, null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField repChar;
    private javax.swing.JLabel repLabel;
    private javax.swing.JCheckBox replace;
    private javax.swing.JSpinner thresholdSpinner;
    // End of variables declaration//GEN-END:variables
    
}
