/*
 * CMLSitePanel.java
 *
 * Created on 07 September 2007, 10:06
 */

package topali.gui.dialog.jobs.cml;

import topali.data.*;
import topali.gui.Icons;

/**
 *
 * @author  dlindn
 */
public class CMLSitePanel extends javax.swing.JPanel {
    
    CMLSiteDialog parent;
    CodeMLResult res;
    
    CMLModel mod0, mod1a, mod2a, mod3, mod7, mod8;
    
    /** Creates new form CMLSitePanel */
    public CMLSitePanel(CodeMLResult res, CMLSiteDialog parent) {
        this.res = (res==null) ? new CodeMLResult(CodeMLResult.TYPE_SITEMODEL) : res;
        this.parent = parent;
        
        initComponents();
        
        setDefaults();
			
        if(res!=null)
        	initPreviousResult(res);
    }
    
    public void setDefaults() {
    	mod0 = new CMLModel(CMLModel.MODEL_M0);
		mod1a = new CMLModel(CMLModel.MODEL_M1a);
		mod2a = new CMLModel(CMLModel.MODEL_M2a);
		mod3 = new CMLModel(CMLModel.MODEL_M3);
		mod7 = new CMLModel(CMLModel.MODEL_M7);
		mod8 = new CMLModel(CMLModel.MODEL_M8);
		
		m0.setSelected(false);
		m1a.setSelected(true);
		m7.setSelected(false);
    }
    
    public CodeMLResult getResult() {
 
    	if(m0.isSelected()) {
    		res.models.addAll(mod0.generateModels());
    		res.models.addAll(mod3.generateModels());
    	}
    	if(m1a.isSelected()) {
    		res.models.addAll(mod1a.generateModels());
    		res.models.addAll(mod2a.generateModels());
    	}	
    	if(m7.isSelected()) {
    		res.models.addAll(mod7.generateModels());
    		res.models.addAll(mod8.generateModels());
    	}
    	
    	return res;
    }
    
    private void initPreviousResult(CodeMLResult res) {
		m0.setSelected(false);
		m1a.setSelected(false);
		m7.setSelected(false);
		
		for(CMLModel m : res.models) {
			if(m.model.equals(mod0.model)) {
				m0.setSelected(true);
				mod0 = m;
			}
			if(m.model.equals(mod1a.model)) {
				m1a.setSelected(true);
				mod1a = m;
			}
			if(m.model.equals(mod2a.model)) {
				m1a.setSelected(true);
				mod2a = m;
			}
			if(m.model.equals(mod3.model)) {
				m0.setSelected(true);
				mod3 = m;
			}
			if(m.model.equals(mod7.model)) {
				m7.setSelected(true);
				mod7 = m;
			}
			if(m.model.equals(mod8.model)) {
				m7.setSelected(true);
				mod8 = m;
			}
		}
	}
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        m0set = new javax.swing.JButton();
        m3set = new javax.swing.JButton();
        m0 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        m1a = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m1aset = new javax.swing.JButton();
        m2aset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        m7 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        m7set = new javax.swing.JButton();
        m8set = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        m0set.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Java\\TOPALi\\res\\icons\\settings.png")); // NOI18N
        m0set.setToolTipText("Edit omega start values");
        m0set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m0setActionPerformed(evt);
            }
        });

        m3set.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Java\\TOPALi\\res\\icons\\settings.png")); // NOI18N
        m3set.setToolTipText("Edit omega start values");
        m3set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3setActionPerformed(evt);
            }
        });

        m0.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        m0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        m0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                m0StateChanged(evt);
            }
        });

        jLabel1.setText("M0 (One Ratio)");

        jLabel2.setText("M3 (Discrete, 3 Categories)");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(m0)
                .add(19, 19, 19)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2))
                .add(48, 48, 48)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(m3set)
                    .add(m0set))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(m0)
                    .add(jLabel1)
                    .add(m0set))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(m3set))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        m1a.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        m1a.setMargin(new java.awt.Insets(0, 0, 0, 0));
        m1a.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                m1aStateChanged(evt);
            }
        });

        jLabel3.setText("M1a (Nearly Neutral)");

        jLabel4.setText("M2a (Positive Selection)");

        m1aset.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Java\\TOPALi\\res\\icons\\settings.png")); // NOI18N
        m1aset.setToolTipText("Edit omega start values");
        m1aset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1asetActionPerformed(evt);
            }
        });

        m2aset.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Java\\TOPALi\\res\\icons\\settings.png")); // NOI18N
        m2aset.setToolTipText("Edit omega start values");
        m2aset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2asetActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(m1a)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel4))
                .add(67, 67, 67)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(m2aset)
                    .add(m1aset))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(m1a)
                    .add(jLabel3)
                    .add(m1aset))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(m2aset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        m7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        m7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        m7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                m7StateChanged(evt);
            }
        });

        jLabel5.setText("M7 (Beta, 10 Categories)");

        jLabel6.setText("M8 (Beta & w>1, 11 Categories)");

        m7set.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Java\\TOPALi\\res\\icons\\settings.png")); // NOI18N
        m7set.setToolTipText("Edit omega start values");
        m7set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m7setActionPerformed(evt);
            }
        });

        m8set.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Java\\TOPALi\\res\\icons\\settings.png")); // NOI18N
        m8set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m8setActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(m7)
                .add(17, 17, 17)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jLabel6))
                .add(26, 26, 26)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(m7set)
                    .add(m8set))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(m7)
                    .add(jLabel5)
                    .add(m7set))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(m8set))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void m7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_m7StateChanged
        checkSelected();
    }//GEN-LAST:event_m7StateChanged

    private void m1aStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_m1aStateChanged
        checkSelected();
    }//GEN-LAST:event_m1aStateChanged

    private void m0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_m0StateChanged
        checkSelected();
    }//GEN-LAST:event_m0StateChanged

    private void checkSelected() {
    	if(parent.bRun!=null)
    		parent.bRun.setEnabled(m0.isSelected() || m1a.isSelected() || m7.isSelected());
    }
    
    private void m8setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m8setActionPerformed
        OmegaValuesDialog dlg = new OmegaValuesDialog(parent, true, mod8);
        dlg.setVisible(true);
        if(dlg.getModel()!=null)
            mod8 = dlg.getModel();
    }//GEN-LAST:event_m8setActionPerformed

    private void m7setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m7setActionPerformed
        OmegaValuesDialog dlg = new OmegaValuesDialog(parent, true, mod7);
        dlg.setVisible(true);
        if(dlg.getModel()!=null)
            mod7 = dlg.getModel();
    }//GEN-LAST:event_m7setActionPerformed

    private void m3setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3setActionPerformed
        OmegaValuesDialog dlg = new OmegaValuesDialog(parent, true, mod3);
        dlg.setVisible(true);
        if(dlg.getModel()!=null)
            mod3 = dlg.getModel();
    }//GEN-LAST:event_m3setActionPerformed

    private void m2asetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2asetActionPerformed
        OmegaValuesDialog dlg = new OmegaValuesDialog(parent, true, mod2a);
        dlg.setVisible(true);
        if(dlg.getModel()!=null)
            mod2a = dlg.getModel();
    }//GEN-LAST:event_m2asetActionPerformed

    private void m1asetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1asetActionPerformed
        OmegaValuesDialog dlg = new OmegaValuesDialog(parent, true, mod1a);
        dlg.setVisible(true);
        if(dlg.getModel()!=null)
            mod1a = dlg.getModel();
    }//GEN-LAST:event_m1asetActionPerformed

    private void m0setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m0setActionPerformed
        OmegaValuesDialog dlg = new OmegaValuesDialog(parent, true, mod0);
        dlg.setVisible(true);
        if(dlg.getModel()!=null)
            mod0 = dlg.getModel();
    }//GEN-LAST:event_m0setActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox m0;
    private javax.swing.JButton m0set;
    private javax.swing.JCheckBox m1a;
    private javax.swing.JButton m1aset;
    private javax.swing.JButton m2aset;
    private javax.swing.JButton m3set;
    private javax.swing.JCheckBox m7;
    private javax.swing.JButton m7set;
    private javax.swing.JButton m8set;
    // End of variables declaration//GEN-END:variables
    
}
