/*
 * EditCodRegDialog.java
 *
 * Created on 25 February 2008, 09:26
 */

package topali.gui.dialog.annotation;

import java.util.List;
import javax.swing.*;
import scri.commons.gui.MsgBox;
import topali.data.AlignmentData;
import topali.data.annotations.CodingRegionAnnotation;
import topali.data.models.*;
import topali.var.utils.Utils;

/**
 *
 * @author  dlindn
 */
public class EditCodRegDialog extends javax.swing.JDialog {
    
	int aStart, aEnd;
	String aM1, aM2, aM3;
	boolean aM1Gamma, aM2Gamma, aM3Gamma;
	boolean aM1Inv, aM2Inv, aM3Inv;
	String aComment;
	
	public boolean cancelled = true;
	
    /** Creates new form EditCodRegDialog */
    public EditCodRegDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getRootPane().setDefaultButton(bOk);
    	Utils.addCloseHandler(this, bCancel);
    }
    
    public void init(CodingRegionAnnotation anno, AlignmentData data) {
    	if(anno!=null) {
    		SpinnerNumberModel mod1 = new SpinnerNumberModel(anno.getStart(), 1, data.getSequenceSet().getLength(), 1);
    		start.setModel(mod1);
    		SpinnerNumberModel mod2 = new SpinnerNumberModel(anno.getEnd(), 1, data.getSequenceSet().getLength(), 1);
    		end.setModel(mod2);
    		if(anno.getComment()!=null)
    			comment.setText(anno.getComment());
    		
    		List<Model> models = ModelManager.getInstance().listDNAModels();
    		
    		if(models!=null) {
    			String[] modNames = new String[models.size()];
    			int sel1=-1, sel2=-1, sel3=-1;
    			for(int i=0; i<modNames.length; i++) {
    				modNames[i] = models.get(i).getName();
    				
    				if(modNames[i].equals(anno.getModC1().getName()))
    					sel1 = i;
    				if(modNames[i].equals(anno.getModC2().getName()))
    					sel2 = i;
    				if(modNames[i].equals(anno.getModC3().getName()))
    					sel3 = i;
    			}
    			DefaultComboBoxModel mod3 = new DefaultComboBoxModel(modNames);
    			DefaultComboBoxModel mod4 = new DefaultComboBoxModel(modNames);
    			DefaultComboBoxModel mod5 = new DefaultComboBoxModel(modNames);
    			m1Type.setModel(mod3);
    			m2Type.setModel(mod4);
    			m3Type.setModel(mod5);

    			if(sel1>-1)
    				m1Type.setSelectedIndex(sel1);
    			if(sel2>-1)
    				m2Type.setSelectedIndex(sel2);
    			if(sel3>-1)
    				m3Type.setSelectedIndex(sel3);
    			
    			m1Gamma.setSelected(anno.getModC1().isGamma());
    			m1Inv.setSelected(anno.getModC1().isInv());
    			m2Gamma.setSelected(anno.getModC2().isGamma());
    			m2Inv.setSelected(anno.getModC2().isInv());
    			m3Gamma.setSelected(anno.getModC3().isGamma());
    			m3Inv.setSelected(anno.getModC3().isInv());
    		}
    	}
    	
    	else {
    		SpinnerNumberModel mod1 = new SpinnerNumberModel(1, 1, data.getSequenceSet().getLength(), 1);
    		start.setModel(mod1);
    		SpinnerNumberModel mod2 = new SpinnerNumberModel(data.getSequenceSet().getLength(), 1, data.getSequenceSet().getLength(), 1);
    		end.setModel(mod2);
    		
    		List<Model> models = null;
    		if(data.getSequenceSet().getProps().isNucleotides()) {
    			models = ModelManager.getInstance().listDNAModels();
    		}
    		else if(data.getSequenceSet().getProps().isProtein()) {
    			models = ModelManager.getInstance().listProteinModels();
    		}
    		
    		if(models!=null) {
    			Model defModel = data.getSequenceSet().getProps().getModel();
    			String[] modNames = new String[models.size()];
    			int sel=-1;
    			for(int i=0; i<modNames.length; i++) {
    				modNames[i] = models.get(i).getName();
    				
    				if(modNames[i].equals(defModel.getName()))
    					sel = i;
    			}
    			DefaultComboBoxModel mod3 = new DefaultComboBoxModel(modNames);
    			DefaultComboBoxModel mod4 = new DefaultComboBoxModel(modNames);
    			DefaultComboBoxModel mod5 = new DefaultComboBoxModel(modNames);
    			m1Type.setModel(mod3);
    			m2Type.setModel(mod4);
    			m3Type.setModel(mod5);
    			
    			if(sel>-1) {
    				m1Type.setSelectedIndex(sel);
    				m2Type.setSelectedIndex(sel);
    				m3Type.setSelectedIndex(sel);
    			}
    			
    			m1Gamma.setSelected(defModel.isGamma());
    			m1Inv.setSelected(defModel.isInv());
    			m2Gamma.setSelected(defModel.isGamma());
    			m2Inv.setSelected(defModel.isInv());
    			m3Gamma.setSelected(defModel.isGamma());
    			m3Inv.setSelected(defModel.isInv());
    		}
    	}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        end = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        comment = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        m1Type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        m1Gamma = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        m1Inv = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        m2Type = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        m2Gamma = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        m2Inv = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        m3Type = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        m3Gamma = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        m3Inv = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(topali.i18n.Text.get("EditCodRegDialog.11"));

        bOk.setText(topali.i18n.Text.get("ok"));
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        bCancel.setText(topali.i18n.Text.get("cancel"));
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel1.setText(topali.i18n.Text.get("EditCodRegDialog.1"));

        jLabel2.setText(topali.i18n.Text.get("EditCodRegDialog.2"));

        comment.setColumns(20);
        comment.setRows(5);
        jScrollPane1.setViewportView(comment);

        jLabel5.setText(topali.i18n.Text.get("EditCodRegDialog.10"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(topali.i18n.Text.get("EditCodRegDialog.4")));

        jLabel3.setText(topali.i18n.Text.get("EditCodRegDialog.7"));

        m1Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText(topali.i18n.Text.get("EditCodRegDialog.8"));

        m1Gamma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1GammaActionPerformed(evt);
            }
        });

        jLabel6.setText(topali.i18n.Text.get("EditCodRegDialog.9"));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(28, 28, 28)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(m1Type, 0, 159, Short.MAX_VALUE)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(1, 1, 1)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(m1Inv)
                                    .add(m1Gamma)))))
                    .add(jLabel6))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(m1Type, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(m1Gamma))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel6)
                        .add(7, 7, 7))
                    .add(m1Inv)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(topali.i18n.Text.get("EditCodRegDialog.5")));

        jLabel7.setText(topali.i18n.Text.get("EditCodRegDialog.7"));

        m2Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText(topali.i18n.Text.get("EditCodRegDialog.8"));

        m2Gamma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2GammaActionPerformed(evt);
            }
        });

        jLabel9.setText(topali.i18n.Text.get("EditCodRegDialog.9"));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel8))
                        .add(28, 28, 28)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(m2Type, 0, 159, Short.MAX_VALUE)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(1, 1, 1)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(m2Inv)
                                    .add(m2Gamma)))))
                    .add(jLabel9))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(m2Type, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(m2Gamma))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel9)
                        .add(7, 7, 7))
                    .add(m2Inv)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(topali.i18n.Text.get("EditCodRegDialog.6")));

        jLabel10.setText(topali.i18n.Text.get("EditCodRegDialog.7"));

        m3Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText(topali.i18n.Text.get("EditCodRegDialog.8"));

        m3Gamma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3GammaActionPerformed(evt);
            }
        });

        jLabel12.setText(topali.i18n.Text.get("EditCodRegDialog.9"));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(jLabel11))
                        .add(28, 28, 28)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(m3Type, 0, 159, Short.MAX_VALUE)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(1, 1, 1)
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(m3Inv)
                                    .add(m3Gamma)))))
                    .add(jLabel12))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(m3Type, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel11)
                    .add(m3Gamma))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel12)
                        .add(7, 7, 7))
                    .add(m3Inv)))
        );

        jLabel13.setText(topali.i18n.Text.get("EditCodRegDialog.3"));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel13)
                    .add(jLabel5)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(start, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .add(end, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(start, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(end, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(bOk)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 291, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bCancel)
                    .add(bOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        aStart = (Integer)start.getValue();
        aEnd = (Integer)end.getValue();
        
        if((aEnd-aStart+1)%3!=0) {
        	MsgBox.msg("The length of a coding region must be dividable by 3.", MsgBox.ERR);
        	return;
        }
        
        aM1 = (String)m1Type.getSelectedItem();
        aM1Gamma = m1Gamma.isSelected();
        aM1Inv = m1Inv.isSelected();
        aM2 = (String)m2Type.getSelectedItem();
        aM2Gamma = m2Gamma.isSelected();
        aM2Inv = m2Inv.isSelected();
        aM3 = (String)m3Type.getSelectedItem();
        aM3Gamma = m3Gamma.isSelected();
        aM3Inv = m3Inv.isSelected();
        
        aComment = comment.getText();
        if(aComment.trim().equals(""))
            aComment = null;
        
        cancelled = false;
        
        setVisible(false);
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void m1GammaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1GammaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_m1GammaActionPerformed

    private void m2GammaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2GammaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_m2GammaActionPerformed

    private void m3GammaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3GammaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_m3GammaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCodRegDialog dialog = new EditCodRegDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JTextArea comment;
    private javax.swing.JSpinner end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox m1Gamma;
    private javax.swing.JCheckBox m1Inv;
    private javax.swing.JComboBox m1Type;
    private javax.swing.JCheckBox m2Gamma;
    private javax.swing.JCheckBox m2Inv;
    private javax.swing.JComboBox m2Type;
    private javax.swing.JCheckBox m3Gamma;
    private javax.swing.JCheckBox m3Inv;
    private javax.swing.JComboBox m3Type;
    private javax.swing.JSpinner start;
    // End of variables declaration//GEN-END:variables
    
}
