#!/bin/bash

echo ""
echo "Compiling BAMBE..."
cd bambe
make

echo ""
echo "Compiling BARCE..."
cd ../barce
make

echo ""
echo "Compiling Fitch..."
cd ../fitch
make

echo ""
echo "Compiling TreeDist..."
cd ../treedist
make

echo ""
echo "Compiling MrBayes"
cd ../mrbayes
make

echo ""
echo "Compiling CodeML"
cd ../codeml
make

echo ""
echo "Compiling CodonW"
cd ../codonW
make

echo ""
echo "Compiling FastML"
cd ../fastml
g++ -o fastml -O3 *.cpp
